[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
# runner = "qemu-system-riscv32 -machine sifive_e,revb=true -nographic -semihosting-config enable=on,target=native -kernel" # Uncomment for QEMU
# runner = "riscv64-unknown-elf-gdb -q -x hifive1-examples/gdb_init" # Uncomment for hardware (no semihosting)
# runner = "riscv64-unknown-elf-gdb -q -x hifive1-examples/gdb_init_sh" # Uncomment for hardware (semihosting)
# runner = "cargo objcopy --release -- -O ihex app.hex"
rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    # "-C",
    # "link-arg=--nmagic",
]

[build]
target = "riscv32imc-unknown-none-elf"
