[package]
edition = "2021"
name = "mik32-rt-examples"
version = "0.1.0"
publish = false

[dependencies]
riscv = { version = "0.15.0" }
mik32-rt-macros = { version = "0.5.0", path = ".././macros" }
mik32v2-pac = { version = "0.0.2" }
mik32-rt ={ path = ".." }


